# Generated by Django 5.2.10 on 2026-01-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0002_interview_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="application_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interview",
            name="pipeline_stage",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("screening", "Phone Screening"),
                    ("technical", "Technical Interview"),
                    ("onsite", "Onsite Interview"),
                    ("final", "Final Round"),
                    ("offer", "Offer Received"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
    ]
