# Generated by Django 5.2.10 on 2026-01-07 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0003_interview_application_date_interview_pipeline_stage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="reminder_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether an email reminder has been sent for this interview",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email reminders for upcoming interviews",
                    ),
                ),
                (
                    "reminder_days_before",
                    models.PositiveIntegerField(
                        default=1, help_text="Days before interview to send reminder"
                    ),
                ),
                (
                    "reminder_time",
                    models.TimeField(
                        default="09:00",
                        help_text="Preferred time to receive reminders (24h format)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
