# Generated by Django 5.2.10 on 2026-01-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0004_interview_reminder_sent_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("offer", "Offer Received"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("declined", "Declined"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="interview_stage",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("screening", "Phone Screening"),
                    ("technical", "Technical Interview"),
                    ("onsite", "Onsite Interview"),
                    ("final", "Final Round"),
                    ("completed", "Completed"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="interview_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interview",
            name="interview_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("phone", "Phone Screen"),
                    ("technical", "Technical"),
                    ("behavioral", "Behavioral"),
                    ("final", "Final Round"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("onsite", "On-site"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
