# Generated by Django 5.2.10 on 2026-01-31 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0007_rename_models_and_update_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="feedback",
            field=models.TextField(
                blank=True,
                help_text="Feedback received or personal notes about how it went",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="job_application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to="interviews.jobapplication",
            ),
        ),
    ]
